force-app/main/form-builder/objects/Form_Definition__c/Form_Definition__c.object-meta.xml
<CustomObject>
    <label>Form Definition</label>
    <nameField>
        <label>Form Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Form_Response__c/Form_Response__c.object-meta.xml
<CustomObject>
    <label>Form Response</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Form_Response__c/fields/Form_Definition__c.field-meta.xml
<CustomField>
    <fullName>Form_Definition__c</fullName>
    <label>Form Definition</label>
    <referenceTo>Form_Definition__c</referenceTo>
    <relationshipLabel>Form Responses</relationshipLabel>
    <relationshipName>Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Form_Section__c/Form_Section__c.object-meta.xml
<CustomObject>
    <label>Form Section</label>
    <nameField>
        <label>Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Form_Section__c/fields/Form_Definition__c.field-meta.xml
<CustomField>
    <fullName>Form_Definition__c</fullName>
    <label>Form Definition</label>
    <referenceTo>Form_Definition__c</referenceTo>
    <relationshipLabel>Form Sections</relationshipLabel>
    <relationshipName>Form_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/Question_Answer__c.object-meta.xml
<CustomObject>
    <label>Question/Answer</label>
    <nameField>
        <displayFormat>Q/A-{0000}</displayFormat>
        <label>Question/Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions/Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/fields/Form_Response__c.field-meta.xml
<CustomField>
    <fullName>Form_Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Response</label>
    <referenceTo>Form_Response__c</referenceTo>
    <relationshipLabel>Questions/Answers</relationshipLabel>
    <relationshipName>Questions_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description
  >Order in which the question answer should be displayed. Copied from Question_Catalog__c.Order__c when the answer is saved.</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Shows the text of the question</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/fields/Question_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Question_Catalog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Question Catalog</description>
    <label>Question Catalog</label>
    <referenceTo>Question_Catalog__c</referenceTo>
    <relationshipLabel>Questions/Answers</relationshipLabel>
    <relationshipName>Questions_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/Question_Catalog__c.object-meta.xml
<CustomObject>
    <label>Question Catalog</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Catalog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Form_Definition__c.field-meta.xml
<CustomField>
    <fullName>Form_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Form Definition</label>
    <referenceTo>Form_Definition__c</referenceTo>
    <relationshipLabel>Question Catalogs</relationshipLabel>
    <relationshipName>Question_Catalogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Form_Section__c.field-meta.xml
<CustomField>
    <fullName>Form_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Form_Section__c.Form_Definition__c</field>
            <operation>equals</operation>
            <valueField>$Source.Form_Definition__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Form_Section__c</referenceTo>
    <relationshipLabel>Question Catalogs</relationshipLabel>
    <relationshipName>Question_Catalogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description
  >Order in which the question will be shown on the form.</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description
  >This field will contain the text that will be shown on forms as questions.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/Question_Rule__c.object-meta.xml
<CustomObject>
    <label>Question Rule</label>
    <nameField>
        <label>Question Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Rule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Logic_Type__c.field-meta.xml
<CustomField>
    <fullName>Logic_Type__c</fullName>
    <label>Logic Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Always</fullName>
                <default>true</default>
                <label>Always</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Question_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Question_Catalog__c</fullName>
    <label>Question Catalog</label>
    <referenceTo>Question_Catalog__c</referenceTo>
    <relationshipLabel>Question Rules</relationshipLabel>
    <relationshipName>Question_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Rule_Type__c</fullName>
    <label>Rule Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>ReadOnly</fullName>
            </value>
            <value>
                <fullName>Autopopulated</fullName>
            </value>
            <value>
                <fullName>Overwrite Picklist Values</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/Rule_Condition__c.object-meta.xml
<CustomObject>
    <label>Rule Condition</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Rule Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>GreaterThan</fullName>
            </value>
            <value>
                <fullName>GreaterOrEqual</fullName>
            </value>
            <value>
                <fullName>LessThan</fullName>
            </value>
            <value>
                <fullName>LessOrEqual</fullName>
            </value>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>IncludesAny</fullName>
            </value>
            <value>
                <fullName>IncludesAll</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>StartsWith</fullName>
            </value>
            <value>
                <fullName>EndsWith</fullName>
            </value>
            <value>
                <fullName>IsBlank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Question_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Question_Catalog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Catalog</label>
    <referenceTo>Question_Catalog__c</referenceTo>
    <relationshipLabel>Rule Conditions</relationshipLabel>
    <relationshipName>Rule_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Question_Rule__c.field-meta.xml
<CustomField>
    <fullName>Question_Rule__c</fullName>
    <label>Question Rule</label>
    <referenceTo>Question_Rule__c</referenceTo>
    <relationshipLabel>Rule Conditions</relationshipLabel>
    <relationshipName>Rule_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/classes/CTSI_QuestionCatalogControllerTest.cls
@IsTest
private class CTSI_QuestionCatalogControllerTest {
  private static final String TEST_USER_NAME_PREFIX = 'standarduser_catalog_test';

  @TestSetup
  static void setup() {
    createStandardUser();
  }

  private static void setupData() {
    System.runAs(getStandardUser()) {
      Form_Definition__c fd = new Form_Definition__c(Name = 'Test Form');
      insert fd;

      Form_Section__c fs = new Form_Section__c(
        Name = 'Section 1',
        Form_Definition__c = fd.Id
      );
      insert fs;

      Question_Catalog__c qc1 = new Question_Catalog__c(
        Form_Definition__c = fd.Id,
        Form_Section__c = fs.Id,
        Question__c = 'Question 1',
        Order__c = 1,
        Active__c = true
      );
      Question_Catalog__c qc2 = new Question_Catalog__c(
        Form_Definition__c = fd.Id,
        Form_Section__c = fs.Id,
        Question__c = 'Question 2',
        Order__c = 2,
        Active__c = true
      );
      insert new List<Question_Catalog__c>{ qc1, qc2 };

      Form_Response__c fr = new Form_Response__c(Form_Definition__c = fd.Id);
      insert fr;

      Question_Answer__c qa = new Question_Answer__c(
        Form_Response__c = fr.Id,
        Question_Catalog__c = qc1.Id,
        Answer__c = 'Answer 1'
      );
      insert qa;

      Question_Rule__c qr = new Question_Rule__c(
        Question_Catalog__c = qc2.Id,
        Rule_Type__c = 'Hidden',
        Logic_Type__c = 'AND',
        Active__c = true
      );
      insert qr;

      Rule_Condition__c rc = new Rule_Condition__c(
        Question_Rule__c = qr.Id,
        Question_Catalog__c = qc1.Id,
        Operator__c = 'Equals',
        Value__c = 'Answer 1',
        Order__c = 1
      );
      insert rc;
    }
  }

  private static User createStandardUser() {
    String uniqueUserName =
      TEST_USER_NAME_PREFIX +
      DateTime.now().getTime() +
      '@testorg.com';
    Profile standardProfile = [
      SELECT Id
      FROM Profile
      WHERE Name = 'System Administrator'
    ];
    User u = new User(
      Alias = 'standt',
      Email = 'standarduser@testorg.com',
      EmailEncodingKey = 'UTF-8',
      LastName = 'Testing',
      LanguageLocaleKey = 'en_US',
      LocaleSidKey = 'en_US',
      ProfileId = standardProfile.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      UserName = uniqueUserName
    );
    insert u;

    PermissionSet ps = [
      SELECT Id
      FROM PermissionSet
      WHERE Name = 'Form_Builder_Edit_Forms'
    ];
    insert new PermissionSetAssignment(
      AssigneeId = u.Id,
      PermissionSetId = ps.Id
    );

    return u;
  }

  private static User getStandardUser() {
    return [
      SELECT Id
      FROM User
      WHERE UserName LIKE :TEST_USER_NAME_PREFIX + '%'
      LIMIT 1
    ];
  }

  @IsTest
  static void testGetCatalogAndAnswers() {
    setupData();
    User standarduser = getStandardUser();

    System.runAs(standarduser) {
      Form_Definition__c fd = [SELECT Id FROM Form_Definition__c LIMIT 1];
      Form_Response__c fr = [SELECT Id FROM Form_Response__c LIMIT 1];

      Test.startTest();
      CTSI_QuestionCatalogController.Response response = CTSI_QuestionCatalogController.getCatalogAndAnswers(
        fd.Id,
        fr.Id,
        new List<String>{ 'Section 1' }
      );
      Test.stopTest();

      Assert.isNotNull(response, 'Response should not be null');
      Assert.areEqual(2, response.catalog.size(), 'Should return 2 questions');
      Assert.areEqual(1, response.answers.size(), 'Should return 1 answer');
      Assert.areEqual(1, response.rules.size(), 'Should return 1 rule');
      Assert.areEqual(
        1,
        response.rules[0].Rule_Conditions__r.size(),
        'Rule should have 1 condition'
      );
    }
  }

  @IsTest
  static void testGetCatalogAndAnswersNoSections() {
    setupData();
    User standarduser = getStandardUser();

    System.runAs(standarduser) {
      Form_Definition__c fd = [SELECT Id FROM Form_Definition__c LIMIT 1];
      Form_Response__c fr = [SELECT Id FROM Form_Response__c LIMIT 1];

      Test.startTest();
      CTSI_QuestionCatalogController.Response response = CTSI_QuestionCatalogController.getCatalogAndAnswers(
        fd.Id,
        fr.Id,
        new List<String>()
      );
      Test.stopTest();

      Assert.isNotNull(response, 'Response should not be null');
      Assert.areEqual(2, response.catalog.size(), 'Should return 2 questions');
    }
  }

  @IsTest
  static void testGetCatalogAndAnswersNullId() {
    setupData();
    User standarduser = getStandardUser();

    System.runAs(standarduser) {
      Test.startTest();
      CTSI_QuestionCatalogController.Response response = CTSI_QuestionCatalogController.getCatalogAndAnswers(
        null,
        null,
        new List<String>()
      );
      Test.stopTest();

      Assert.isNotNull(response, 'Response should not be null');
      Assert.isNull(
        response.catalog,
        'Catalog should be null when formDefinitionId is null'
      );
    }
  }
}