force-app/main/form-builder/objects/Form_Definition__c/Form_Definition__c.object-meta.xml
<CustomObject>
    <label>Form Definition</label>
    <nameField>
        <label>Form Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Catalog__c/Question_Catalog__c.object-meta.xml
<CustomObject>
    <label>Question Catalog</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Catalog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Form_Definition__c.field-meta.xml
<CustomField>
    <fullName>Form_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Form Definition</label>
    <referenceTo>Form_Definition__c</referenceTo>
    <relationshipLabel>Question Catalogs</relationshipLabel>
    <relationshipName>Question_Catalogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description
  >Order in which the question will be shown on the form.</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description
  >This field will contain the text that will be shown on forms as questions.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/Question_Rule__c.object-meta.xml
<CustomObject>
    <label>Question Rule</label>
    <nameField>
        <label>Question Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Rule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Autopopulate_Source_Path__c.field-meta.xml
<CustomField>
    <fullName>Autopopulate_Source_Path__c</fullName>
    <label>Autopopulate Source Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Autopopulate_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Autopopulate_Source_Type__c</fullName>
    <label>Autopopulate Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Raw</fullName>
                <default>true</default>
                <label>Raw</label>
            </value>
            <value>
                <fullName>Context</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Autopopulate_Value_Raw__c.field-meta.xml
<CustomField>
    <fullName>Autopopulate_Value_Raw__c</fullName>
    <label>Autopopulate Value Raw</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Condition_Logic__c.field-meta.xml
<CustomField>
    <fullName>Condition_Logic__c</fullName>
    <label>Condition Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Logic_Type__c.field-meta.xml
<CustomField>
    <fullName>Logic_Type__c</fullName>
    <label>Logic Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Always</fullName>
                <default>true</default>
                <label>Always</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Question_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Question_Catalog__c</fullName>
    <label>Question Catalog</label>
    <referenceTo>Question_Catalog__c</referenceTo>
    <relationshipLabel>Question Rules</relationshipLabel>
    <relationshipName>Question_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Rule_Type__c</fullName>
    <label>Rule Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>ReadOnly</fullName>
            </value>
            <value>
                <fullName>Autopopulated</fullName>
            </value>
            <value>
                <fullName>Overwrite Picklist Values</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/Rule_Condition__c.object-meta.xml
<CustomObject>
    <label>Rule Condition</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Rule Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Not__c.field-meta.xml
<CustomField>
    <fullName>Not__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equals</fullName>
            </value>
            <value>
                <fullName>GreaterThan</fullName>
            </value>
            <value>
                <fullName>GreaterOrEqual</fullName>
            </value>
            <value>
                <fullName>LessThan</fullName>
            </value>
            <value>
                <fullName>LessOrEqual</fullName>
            </value>
            <value>
                <fullName>Includes</fullName>
            </value>
            <value>
                <fullName>IncludesAny</fullName>
            </value>
            <value>
                <fullName>IncludesAll</fullName>
            </value>
            <value>
                <fullName>Contains</fullName>
            </value>
            <value>
                <fullName>StartsWith</fullName>
            </value>
            <value>
                <fullName>EndsWith</fullName>
            </value>
            <value>
                <fullName>IsBlank</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Question_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Question_Catalog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Catalog</label>
    <referenceTo>Question_Catalog__c</referenceTo>
    <relationshipLabel>Rule Conditions</relationshipLabel>
    <relationshipName>Rule_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Question_Rule__c.field-meta.xml
<CustomField>
    <fullName>Question_Rule__c</fullName>
    <label>Question Rule</label>
    <referenceTo>Question_Rule__c</referenceTo>
    <relationshipLabel>Rule Conditions</relationshipLabel>
    <relationshipName>Rule_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Source_Path__c.field-meta.xml
<CustomField>
    <fullName>Source_Path__c</fullName>
    <label>Source Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Source_Type__c</fullName>
    <inlineHelpText
  >Warning: condition will be ignored if context is not given on execution</inlineHelpText>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Answer</fullName>
            </value>
            <value>
                <fullName>Context</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/classes/CTSI_QuestionRulesController.cls
/**
 * @description Controller for question rules
 */
public without sharing class CTSI_QuestionRulesController {
  /**
   * @description fetches question catalog rules and its rule conditions
   * @param questionCatalogId a question catalog id
   * @return List of Question_Rule__c records including conditions
   */
  @AuraEnabled(cacheable=true)
  public static List<Question_Rule__c> getRules(String questionCatalogId) {
    try {
      return [
        SELECT
          Id,
          Name,
          Rule_Type__c,
          Logic_Type__c,
          Condition_Logic__c,
          Question_Catalog__c,
          Active__c,
          Autopopulate_Source_Path__c,
          Autopopulate_Value_Raw__c,
          Autopopulate_Source_Type__c,
          CreatedDate,
          (
            SELECT
              Id,
              Source_Type__c,
              Source_Path__c,
              Operator__c,
              Question_Catalog__c,
              Question_Catalog__r.Question__c,
              Value__c,
              Order__c,
              Not__c
            FROM Rule_Conditions__r
            ORDER BY Order__c ASC
          )
        FROM Question_Rule__c
        WHERE Question_Catalog__c = :questionCatalogId
        WITH USER_MODE
        ORDER BY Active__c DESC, CreatedDate DESC
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description fetches rule conditions for a given question rule
   * @param questionRuleId a question rule id
   * @return A Question_Rule__c record with its rule conditions
   */
  @AuraEnabled(cacheable=true)
  public static Question_Rule__c getRule(String questionRuleId) {
    try {
      return [
        SELECT
          Id,
          Name,
          Rule_Type__c,
          Logic_Type__c,
          Condition_Logic__c,
          Question_Catalog__c,
          Active__c,
          Autopopulate_Source_Path__c,
          Autopopulate_Value_Raw__c,
          Autopopulate_Source_Type__c,
          CreatedDate,
          (
            SELECT
              Id,
              Source_Type__c,
              Source_Path__c,
              Operator__c,
              Question_Catalog__c,
              Question_Catalog__r.Question__c,
              Value__c,
              Order__c,
              Not__c
            FROM Rule_Conditions__r
            ORDER BY Order__c ASC
          )
        FROM Question_Rule__c
        WHERE Id = :questionRuleId
        WITH USER_MODE
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description updates rule conditions for a specific question rule
   * @param questionRuleId the Id of the question rule
   * @param conditions the list of Rule_Condition__c records to insert
   */
  @AuraEnabled
  public static void updateConditions(
    Id questionRuleId,
    List<Rule_Condition__c> conditions
  ) {
    try {
      delete [
        SELECT Id
        FROM Rule_Condition__c
        WHERE Question_Rule__c = :questionRuleId
        WITH USER_MODE
      ];

      insert as user conditions;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description activates a question rule
   * @param questionRuleId the Id of the question rule
   */
  @AuraEnabled
  public static void activate(Id questionRuleId) {
    try {
      update as user new Question_Rule__c(
        Id = questionRuleId,
        Active__c = true
      );
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description deactivates a question rule
   * @param questionRuleId the Id of the question rule
   */
  @AuraEnabled
  public static void deactivate(Id questionRuleId) {
    try {
      update as user new Question_Rule__c(
        Id = questionRuleId,
        Active__c = false
      );
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description deletes a question rule and its associated conditions
   * @param questionRuleId the Id of the question rule to delete
   */
  @AuraEnabled
  public static void deleteRule(Id questionRuleId) {
    try {
      delete as user [
        SELECT Id
        FROM Rule_Condition__c
        WHERE Question_Rule__c = :questionRuleId
        WITH USER_MODE
      ];

      delete as user new Question_Rule__c(Id = questionRuleId);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description gets all rules associated with a specific form definition
   * @param formDefinitionId the Id of the form definition
   * @return List of Question_Rule__c records
   */
  @AuraEnabled(cacheable=true)
  public static List<Question_Rule__c> getRulesByFormDefinition(
    Id formDefinitionId
  ) {
    try {
      return [
        SELECT
          Id,
          Name,
          Rule_Type__c,
          Logic_Type__c,
          Condition_Logic__c,
          Question_Catalog__c,
          Question_Catalog__r.Question__c,
          Active__c,
          Autopopulate_Source_Path__c,
          Autopopulate_Value_Raw__c,
          Autopopulate_Source_Type__c,
          CreatedDate,
          (
            SELECT
              Id,
              Source_Type__c,
              Source_Path__c,
              Operator__c,
              Question_Catalog__c,
              Question_Catalog__r.Question__c,
              Value__c,
              Order__c,
              Not__c
            FROM Rule_Conditions__r
            ORDER BY Order__c ASC
          )
        FROM Question_Rule__c
        WHERE Question_Catalog__r.Form_Definition__c = :formDefinitionId
        WITH USER_MODE
        ORDER BY
          Question_Catalog__r.Order__c ASC,
          Active__c DESC,
          CreatedDate DESC
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description gets active catalog items for a given form
   * @param formDefinitionId the Id of the form definition
   * @return List of active Question_Catalog__c records
   */
  @AuraEnabled(cacheable=true)
  public static List<Question_Catalog__c> getActiveCatalog(
    Id formDefinitionId
  ) {
    try {
      return [
        SELECT Id, Question__c
        FROM Question_Catalog__c
        WHERE
          Form_Definition__c != NULL
          AND Form_Definition__c = :formDefinitionId
          AND Active__c = TRUE
        WITH USER_MODE
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}