force-app/main/src-datatable-sample/objects/DataTest__c/DataTest__c.object-meta.xml
<CustomObject>
    <label>Data Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DataTest__c/fields/Checkbox__c.field-meta.xml
<CustomField>
    <fullName>Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>checkbox field help</inlineHelpText>
    <label>Checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/src-datatable-sample/objects/DataTest__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/DataTest__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>help text</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DataTest__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a</fullName>
            </value>
            <value>
                <fullName>b</fullName>
            </value>
            <value>
                <fullName>c</fullName>
            </value>
            <value>
                <fullName>d</fullName>
            </value>
            <value>
                <fullName>e</fullName>
            </value>
            <value>
                <fullName>fifthValue</fullName>
                <isActive>false</isActive>
                <label>fifthValue</label>
            </value>
            <value>
                <fullName>firstValue</fullName>
                <isActive>false</isActive>
                <label>firstValue</label>
            </value>
            <value>
                <fullName>fourthValue</fullName>
                <isActive>false</isActive>
                <label>fourthValue</label>
            </value>
            <value>
                <fullName>secondValue</fullName>
                <isActive>false</isActive>
                <label>secondValue</label>
            </value>
            <value>
                <fullName>thirdValue</fullName>
                <isActive>false</isActive>
                <label>thirdValue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/TextArea__c.field-meta.xml
<CustomField>
    <fullName>TextArea__c</fullName>
    <label>TextArea</label>
    <type>TextArea</type>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Time</type>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <type>Url</type>
</CustomField>

force-app/main/src-datatable-sample/classes/DatatableSampleController.cls
public with sharing class DatatableSampleController {
  @AuraEnabled(cacheable=true)
  public static List<DataTest__c> getData() {
    try {
      return [
        SELECT
          Checkbox__c,
          CreatedDate,
          Currency__c,
          Date__c,
          Email__c,
          Id,
          LastModifiedBy.Name,
          Name,
          OwnerId,
          Picklist__c,
          PicklistMultiSelect__c,
          TextArea__c,
          Time__c,
          Url__c
        FROM DataTest__c
        LIMIT 25
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}