force-app/main/src-datatable-sample/objects/DataTest__c/DataTest__c.object-meta.xml
<CustomObject>
    <label>Data Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DataTest__c/fields/Checkbox__c.field-meta.xml
<CustomField>
    <fullName>Checkbox__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>checkbox field help</inlineHelpText>
    <label>Checkbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/src-datatable-sample/objects/DataTest__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <inlineHelpText>help text</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <label>DateTime</label>
    <type>DateTime</type>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/Lookup__c.field-meta.xml
<CustomField>
    <fullName>Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup account field description</description>
    <inlineHelpText>this is the help text on the field setup</inlineHelpText>
    <label>Lookup (Account)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Data Tests</relationshipLabel>
    <relationshipName>Data_Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DataTest__c/fields/MultiSelectPicklist__c.field-meta.xml
<CustomField>
    <fullName>MultiSelectPicklist__c</fullName>
    <label>MultiSelectPicklist</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a</fullName>
                <label>first value first value</label>
            </value>
            <value>
                <fullName>b</fullName>
                <label>second value second value</label>
            </value>
            <value>
                <fullName>c</fullName>
                <label>third value third value</label>
            </value>
            <value>
                <fullName>d</fullName>
                <label>fourth value fourth value</label>
            </value>
            <value>
                <fullName>e</fullName>
                <label>fifth value fifth value</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/src-datatable-sample/objects/DataTest__c/fields/Percent__c.field-meta.xml
<CustomField>
    <fullName>Percent__c</fullName>
    <label>Percent</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/DataTest__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>a</fullName>
            </value>
            <value>
                <fullName>b</fullName>
            </value>
            <value>
                <fullName>c</fullName>
            </value>
            <value>
                <fullName>d</fullName>
            </value>
            <value>
                <fullName>e</fullName>
            </value>
            <value>
                <fullName>fifthValue</fullName>
                <isActive>false</isActive>
                <label>fifthValue</label>
            </value>
            <value>
                <fullName>firstValue</fullName>
                <isActive>false</isActive>
                <label>firstValue</label>
            </value>
            <value>
                <fullName>fourthValue</fullName>
                <isActive>false</isActive>
                <label>fourthValue</label>
            </value>
            <value>
                <fullName>secondValue</fullName>
                <isActive>false</isActive>
                <label>secondValue</label>
            </value>
            <value>
                <fullName>thirdValue</fullName>
                <isActive>false</isActive>
                <label>thirdValue</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/TextArea__c.field-meta.xml
<CustomField>
    <fullName>TextArea__c</fullName>
    <label>TextArea</label>
    <type>TextArea</type>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>Time</type>
</CustomField>

src-datatable/main/default/objects/DataTest__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <label>Url</label>
    <type>Url</type>
</CustomField>

src-datatable/main/default/classes/GenerateData.cls
public with sharing class GenerateData {
  private static List<String> emails = new List<String>{
    'ipsen@sbcglobal.net',
    'garland@sbcglobal.net',
    'webinc@optonline.net',
    'nullchar@comcast.net',
    'brbarret@msn.com',
    'mdielmann@hotmail.com',
    'hager@live.com',
    'rnelson@aol.com',
    'tbusch@mac.com',
    'vertigo@icloud.com',
    'nicktrig@hotmail.com',
    'quinn@comcast.net'
  };

  private static List<String> urls = new List<String>{
    'http://www.sample.org/head',
    'http://sample.edu/',
    'http://sample.org/',
    'http://sample.info/?insect=fireman&porter=attraction#cave',
    'http://sample.org/#yak',
    'https://sample.edu/railway',
    'https://sample.edu/day',
    'https://sample.info/#corn',
    'https://sample.org/cover',
    'https://sample.net/#hose'
  };

  private static final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz, .;';

  private static List<String> picklistValues = new List<String>{
    'a',
    'b',
    'c',
    'd',
    'e'
  };

  public static void doWork(Integer numberOfRecords) {
    List<DataTest__c> result = new List<DataTest__c>();
    List<String> accIds = getAccountIds();

    Integer size = picklistValues.size() + 1;

    for (Integer i = 0; i < numberOfRecords; i++) {
      DataTest__c singleResult = new DataTest__c();

      // singleResult.Checkbox__c = Math.mod(Integer.valueof((math.random() * 10)), 2) == 0;
      singleResult.Currency__c = Integer.valueOf(Math.random() * 999);
      singleResult.Date__c = randomDate(
        Date.newInstance(2000, 1, 1),
        Date.newInstance(2025, 1, 1)
      );
      singleResult.Time__c = randomTime(
        Integer.valueOf(Math.random() * 100000),
        Integer.valueOf(Math.random() * 100000)
      );
      singleResult.DateTime__c = DateTime.newInstance(
        singleResult.Date__c.year(),
        singleResult.Date__c.month(),
        singleResult.Date__c.day(),
        singleResult.Time__c.hour(),
        singleResult.Time__c.minute(),
        singleResult.Time__c.second()
      );

      singleResult.Email__c = getRandomElementFromList(emails);
      singleResult.Lookup__c = getRandomElementFromList(accIds);
      singleResult.Name = generateRandomString(
        12 + Integer.valueOf(Math.random() * 5)
      );
      // singleResult.MultiSelectPicklist__c = 'a;b;c;d;e';
      singleResult.Number__c = Integer.valueOf(Math.random() * 1000);
      singleResult.Percent__c = Integer.valueOf(Math.random() * 100);
      singleResult.Phone__c = String.valueOf(
        Integer.valueOf(Math.random() * 100000)
      );
      // singleResult.Picklist__c = getRandomElementFromList(picklistValues);
      // singleResult.Text__c = generateRandomString(12 + Integer.valueOf(Math.random() * 5));
      singleResult.TextArea__c = generateRandomString(
        50 + Integer.valueOf(Math.random() * 10)
      );
      singleResult.Url__c = getRandomElementFromList(urls);

      result.add(singleResult);
    }

    insert result;
  }

  public static Date randomDate(Date minDate, Date maxDate) {
    Integer rangeSize = minDate.daysBetween(maxDate) + 1;
    Decimal daysToAdd = rangeSize * math.Random();
    Date result = minDate.addDays(daysToAdd.intValue());
    return result;
  }

  public static Time randomTime(
    Integer randomNumber,
    Integer anotherRandomNumber
  ) {
    return Time.newInstance(randomNumber, anotherRandomNumber, 0, 0);
  }

  public static String getRandomElementFromList(List<String> values) {
    Integer listSize = values.size() - 1;
    Integer randomNumber = Integer.valueof((Math.random() * listSize));
    return values[randomNumber];
  }

  public static List<String> getAccountIds() {
    List<String> result = new List<String>();

    for (Account acc : [SELECT Id FROM Account]) {
      result.add(acc.Id);
    }

    return result;
  }

  public static String generateRandomString(Integer lengthOfString) {
    String randStr = '';
    while (randStr.length() < lengthOfString) {
      Integer idx = Math.mod(
        Math.abs(Crypto.getRandomInteger()),
        chars.length()
      );
      randStr += chars.substring(idx, idx + 1);
    }
    return randStr;
  }
}