force-app/main/form-builder/objects/Form_Response__c/Form_Response__c.object-meta.xml
<CustomObject>
    <label>Form Response</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Form Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Form_Response__c/fields/Form_Definition__c.field-meta.xml
<CustomField>
    <fullName>Form_Definition__c</fullName>
    <label>Form Definition</label>
    <referenceTo>Form_Definition__c</referenceTo>
    <relationshipLabel>Form Responses</relationshipLabel>
    <relationshipName>Form_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Form_Section__c/Form_Section__c.object-meta.xml
<CustomObject>
    <label>Form Section</label>
    <nameField>
        <label>Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Form_Section__c/fields/Form_Definition__c.field-meta.xml
<CustomField>
    <fullName>Form_Definition__c</fullName>
    <label>Form Definition</label>
    <referenceTo>Form_Definition__c</referenceTo>
    <relationshipLabel>Form Sections</relationshipLabel>
    <relationshipName>Form_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/Question_Answer__c.object-meta.xml
<CustomObject>
    <label>Question/Answer</label>
    <nameField>
        <displayFormat>Q/A-{0000}</displayFormat>
        <label>Question/Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions/Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Answer__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/fields/Form_Response__c.field-meta.xml
<CustomField>
    <fullName>Form_Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Response</label>
    <referenceTo>Form_Response__c</referenceTo>
    <relationshipLabel>Questions/Answers</relationshipLabel>
    <relationshipName>Questions_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description
  >Order in which the question answer should be displayed. Copied from Question_Catalog__c.Order__c when the answer is saved.</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>Shows the text of the question</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Answer__c/fields/Question_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Question_Catalog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Question Catalog</description>
    <label>Question Catalog</label>
    <referenceTo>Question_Catalog__c</referenceTo>
    <relationshipLabel>Questions/Answers</relationshipLabel>
    <relationshipName>Questions_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/Question_Catalog__c.object-meta.xml
<CustomObject>
    <label>Question Catalog</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Question Catalog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Answer_Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Answer_Data_Type__c</fullName>
    <description>Type of answer</description>
    <label>Answer Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date Time</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Radio Buttons</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Display Text</fullName>
            </value>
            <value>
                <fullName>Multi-Select Checkbox</fullName>
            </value>
            <value>
                <fullName>Multi-Select Picklist</fullName>
            </value>
            <value>
                <fullName>Text Area</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <description>Field to which the answer should be mapped</description>
    <label>Field</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Form_Definition__c.field-meta.xml
<CustomField>
    <fullName>Form_Definition__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Form Definition</label>
    <referenceTo>Form_Definition__c</referenceTo>
    <relationshipLabel>Question Catalogs</relationshipLabel>
    <relationshipName>Question_Catalogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Form_Section__c.field-meta.xml
<CustomField>
    <fullName>Form_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Form_Section__c.Form_Definition__c</field>
            <operation>equals</operation>
            <valueField>$Source.Form_Definition__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Form_Section__c</referenceTo>
    <relationshipLabel>Question Catalogs</relationshipLabel>
    <relationshipName>Question_Catalogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Group_By__c.field-meta.xml
<CustomField>
    <fullName>Group_By__c</fullName>
    <description
  >Use this field to group questions together. Questions with the same value will be displayed in the same group. If questions are numeric, currency, or percentage types, their values will be summed at the bottom of the group.</description>
    <label>Group By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Object to which the answer should be mapped</description>
    <label>Object</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description
  >Order in which the question will be shown on the form.</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Values__c</fullName>
    <description
  >Will hold the possible values of the answers to picklist in the form</description>
    <inlineHelpText
  >Add all the picklist values separated by semicolons.</inlineHelpText>
    <label>Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description
  >This field will contain the text that will be shown on forms as questions.</description>
    <label>Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Catalog__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/Question_Rule__c.object-meta.xml
<CustomObject>
    <label>Question Rule</label>
    <nameField>
        <label>Question Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Question_Rule__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Autopopulate_Source_Path__c.field-meta.xml
<CustomField>
    <fullName>Autopopulate_Source_Path__c</fullName>
    <label>Autopopulate Source Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Condition_Logic__c.field-meta.xml
<CustomField>
    <fullName>Condition_Logic__c</fullName>
    <label>Condition Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Logic_Type__c.field-meta.xml
<CustomField>
    <fullName>Logic_Type__c</fullName>
    <label>Logic Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Always</fullName>
                <default>true</default>
                <label>Always</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Overwrite_Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Overwrite_Picklist_Values__c</fullName>
    <label>Overwrite Picklist Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Question_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Question_Catalog__c</fullName>
    <label>Question Catalog</label>
    <referenceTo>Question_Catalog__c</referenceTo>
    <relationshipLabel>Question Rules</relationshipLabel>
    <relationshipName>Question_Rules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Question_Rule__c/fields/Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Rule_Type__c</fullName>
    <label>Rule Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hidden</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>ReadOnly</fullName>
            </value>
            <value>
                <fullName>Autopopulated</fullName>
            </value>
            <value>
                <fullName>Overwrite Picklist Values</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/Rule_Condition__c.object-meta.xml
<CustomObject>
    <label>Rule Condition</label>
    <nameField>
        <displayFormat>RC-{0000}</displayFormat>
        <label>Rule Condition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Question_Catalog__c.field-meta.xml
<CustomField>
    <fullName>Question_Catalog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question Catalog</label>
    <referenceTo>Question_Catalog__c</referenceTo>
    <relationshipLabel>Rule Conditions</relationshipLabel>
    <relationshipName>Rule_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Question_Rule__c.field-meta.xml
<CustomField>
    <fullName>Question_Rule__c</fullName>
    <label>Question Rule</label>
    <referenceTo>Question_Rule__c</referenceTo>
    <relationshipLabel>Rule Conditions</relationshipLabel>
    <relationshipName>Rule_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/form-builder/objects/Rule_Condition__c/fields/Source_Path__c.field-meta.xml
<CustomField>
    <fullName>Source_Path__c</fullName>
    <label>Source Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/form-builder/classes/CTSI_QuestionCatalogController.cls
/**
 * @description Controller for question catalog
 */
public with sharing class CTSI_QuestionCatalogController {
  /**
   * @description fetches question catalog given an specific type and section
   * @param formDefinitionId
   * @param formResponseId
   * @param sections
   * @return response object with catalog and answers (if there are)
   */
  @AuraEnabled(cacheable=true)
  public static Response getCatalogAndAnswers(
    Id formDefinitionId,
    Id formResponseId,
    List<String> sections
  ) {
    try {
      Response result = new Response();
      if (formDefinitionId == null) {
        return result;
      }
      result.catalog = getCatalog(formDefinitionId, new Set<String>(sections));
      result.answers = getAnswers(formResponseId, result.catalog);
      result.rules = getRules(result.catalog);
      return result;
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  private static List<Question_Answer__c> getAnswers(
    Id formResponseId,
    List<Question_Catalog__c> catalog
  ) {
    if (formResponseId == null || catalog.isEmpty()) {
      return new List<Question_Answer__c>();
    }

    return [
      SELECT Id, Question__c, Answer__c, Order__c, Question_Catalog__c
      FROM Question_Answer__c
      WHERE
        Question_Catalog__c IN :catalog
        AND Form_Response__c = :formResponseId
      WITH USER_MODE
    ];
  }

  private static List<Question_Catalog__c> getCatalog(
    Id formDefinitionId,
    Set<String> sections
  ) {
    List<Question_Catalog__c> result = [
      SELECT
        Active__c,
        Answer_Data_Type__c,
        Field__c,
        Group_By__c,
        Id,
        Name,
        Object__c,
        Order__c,
        Picklist_Values__c,
        Question__c,
        Form_Section__r.Name,
        Required__c
      FROM Question_Catalog__c
      WHERE Active__c = TRUE AND Form_Definition__c = :formDefinitionId
      WITH USER_MODE
      ORDER BY Order__c NULLS LAST
    ];

    if (!sections.isEmpty()) {
      List<Question_Catalog__c> filtered = new List<Question_Catalog__c>();

      for (Question_Catalog__c record : result) {
        String sectionName = record.Form_Section__r?.Name;

        if (String.isNotBlank(sectionName) && sections.contains(sectionName)) {
          filtered.add(record);
        }
      }

      result = filtered;
    }

    return result;
  }

  private static List<Question_Rule__c> getRules(
    List<Question_Catalog__c> questionCatalogs
  ) {
    try {
      if (questionCatalogs.isEmpty()) {
        return new List<Question_Rule__c>();
      }

      return [
        SELECT
          Id,
          Name,
          Rule_Type__c,
          Logic_Type__c,
          Condition_Logic__c,
          Question_Catalog__c,
          Overwrite_Picklist_Values__c,
          Active__c,
          Autopopulate_Source_Path__c,
          Autopopulate_Value_Raw__c,
          Autopopulate_Source_Type__c,
          CreatedDate,
          (
            SELECT
              Id,
              Source_Type__c,
              Source_Path__c,
              Operator__c,
              Question_Catalog__r.Question__c,
              Value__c,
              Order__c,
              Not__c
            FROM Rule_Conditions__r
            ORDER BY Order__c ASC
          )
        FROM Question_Rule__c
        WHERE Question_Catalog__c IN :questionCatalogs
        WITH USER_MODE
        ORDER BY Active__c DESC, CreatedDate DESC
      ];
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }

  /**
   * @description Inner class used to wrap catalog items, answers and rules for the front-end
   */
  public class Response {
    @AuraEnabled
    public List<Question_Catalog__c> catalog;
    @AuraEnabled
    public List<Question_Answer__c> answers;
    @AuraEnabled
    public List<Question_Rule__c> rules;
  }
}